//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.TravelAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingImage
    {
        public int Id { get; set; }
        public int BuildingId { get; set; }
        public byte[] ImageSmall { get; set; }
        public byte[] ImageLarge { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
