//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.TravelAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public string UserName { get; set; }
        public int ApartmentId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
