//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.TravelAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public Apartment()
        {
            this.Rent = new HashSet<Rent>();
        }
    
        public int Id { get; set; }
        public int BuildingId { get; set; }
        public int Room { get; set; }
        public int Turnday { get; set; }
        public string Comment { get; set; }
        public int Price { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual ICollection<Rent> Rent { get; set; }
    }
}
