//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.TravelAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public Building()
        {
            this.Apartment = new HashSet<Apartment>();
            this.BuildingImage = new HashSet<BuildingImage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CityId { get; set; }
        public int SeaDistance { get; set; }
        public Nullable<int> ShoreId { get; set; }
        public Nullable<int> Features { get; set; }
        public double LocationX { get; set; }
        public double LocationY { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<Apartment> Apartment { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<BuildingImage> BuildingImage { get; set; }
    }
}
