// Generated by Bisonc++ V4.09.02 on Wed, 07 Dec 2016 18:54:12 +0100

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {295, 5}, // 1: start (OPENBRAC) ->  szignatura OPENBRAC deklaraciok torzs CLOSEBRAC
     {296, 4}, // 2: szignatura (INT) ->  INT MAIN OPENPAR CLOSEPAR
     {297, 0}, // 3: deklaraciok ->  <empty>
     {297, 2}, // 4: deklaraciok ->  deklaracio deklaraciok
     {299, 3}, // 5: deklaracio (UNSIGNED) ->  UNSIGNED ID ENDL
     {299, 3}, // 6: deklaracio (BOOL) ->  BOOL ID ENDL
     {298, 1}, // 7: torzs ->  utasitas
     {298, 2}, // 8: torzs ->  utasitas torzs
     {300, 1}, // 9: utasitas ->  ertekadas
     {300, 1}, // 10: utasitas ->  be
     {300, 1}, // 11: utasitas ->  ki
     {300, 1}, // 12: utasitas ->  elagazas
     {300, 1}, // 13: utasitas ->  ciklus
     {301, 4}, // 14: ertekadas (ID) ->  ID EQV kifejezes ENDL
     {302, 4}, // 15: be (STR_IN) ->  STR_IN CIN ID ENDL
     {303, 4}, // 16: ki (STR_OUT) ->  STR_OUT COUT kifejezes ENDL
     {304, 7}, // 17: elagazas (IF) ->  IF OPENPAR kifejezes CLOSEPAR OPENBRAC torzs CLOSEBRAC
     {304, 11}, // 18: elagazas (IF) ->  IF OPENPAR kifejezes CLOSEPAR OPENBRAC torzs CLOSEBRAC ELSE OPENBRAC torzs CLOSEBRAC
     {305, 7}, // 19: ciklus (WHILE) ->  WHILE OPENPAR kifejezes CLOSEPAR OPENBRAC torzs CLOSEBRAC
     {306, 1}, // 20: kifejezes (NUM) ->  NUM
     {306, 1}, // 21: kifejezes (TRUE) ->  TRUE
     {306, 1}, // 22: kifejezes (FALSE) ->  FALSE
     {306, 1}, // 23: kifejezes (ID) ->  ID
     {306, 3}, // 24: kifejezes (PLS) ->  kifejezes PLS kifejezes
     {306, 3}, // 25: kifejezes (MIN) ->  kifejezes MIN kifejezes
     {306, 3}, // 26: kifejezes (MUL) ->  kifejezes MUL kifejezes
     {306, 3}, // 27: kifejezes (DIV) ->  kifejezes DIV kifejezes
     {306, 3}, // 28: kifejezes (MOD) ->  kifejezes MOD kifejezes
     {306, 3}, // 29: kifejezes (LESS) ->  kifejezes LESS kifejezes
     {306, 3}, // 30: kifejezes (GRT) ->  kifejezes GRT kifejezes
     {306, 3}, // 31: kifejezes (EQUAL) ->  kifejezes EQUAL kifejezes
     {306, 3}, // 32: kifejezes (AND) ->  kifejezes AND kifejezes
     {306, 3}, // 33: kifejezes (OR) ->  kifejezes OR kifejezes
     {306, 2}, // 34: kifejezes (NEG) ->  NEG kifejezes
     {306, 3}, // 35: kifejezes (OPENPAR) ->  OPENPAR kifejezes CLOSEPAR
     {307, 1}, // 36: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 4} },              
    { {       295}, { 1} }, // start     
    { {       296}, { 2} }, // szignatura
    { {       257}, { 3} }, // INT       
    { {         0}, { 0} },              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 2} },            
    { {       259}, { 4} }, // OPENBRAC
    { {         0}, { 0} },            
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 2} },        
    { {       258}, { 5} }, // MAIN
    { {         0}, { 0} },        
};

SR__ s_4[] =
{
    { { REQ_DEF}, {  5} },               
    { {     297}, {  6} }, // deklaraciok
    { {     299}, {  7} }, // deklaracio 
    { {     261}, {  8} }, // UNSIGNED   
    { {     262}, {  9} }, // BOOL       
    { {       0}, { -3} },               
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },           
    { {       272}, { 10} }, // OPENPAR
    { {         0}, {  0} },           
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, { 13} },             
    { {       298}, { 11} }, // torzs    
    { {       300}, { 12} }, // utasitas 
    { {       301}, { 13} }, // ertekadas
    { {       302}, { 14} }, // be       
    { {       303}, { 15} }, // ki       
    { {       304}, { 16} }, // elagazas 
    { {       305}, { 17} }, // ciklus   
    { {       277}, { 18} }, // ID       
    { {       269}, { 19} }, // STR_IN   
    { {       268}, { 20} }, // STR_OUT  
    { {       263}, { 21} }, // IF       
    { {       265}, { 22} }, // WHILE    
    { {         0}, {  0} },             
};

SR__ s_7[] =
{
    { { REQ_DEF}, {  5} },               
    { {     297}, { 23} }, // deklaraciok
    { {     299}, {  7} }, // deklaracio 
    { {     261}, {  8} }, // UNSIGNED   
    { {     262}, {  9} }, // BOOL       
    { {       0}, { -3} },               
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       277}, { 24} }, // ID
    { {         0}, {  0} },      
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       277}, { 25} }, // ID
    { {         0}, {  0} },      
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       273}, { 26} }, // CLOSEPAR
    { {         0}, {  0} },            
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       260}, { 27} }, // CLOSEBRAC
    { {         0}, {  0} },             
};

SR__ s_12[] =
{
    { { REQ_DEF}, { 13} },             
    { {     298}, { 28} }, // torzs    
    { {     300}, { 12} }, // utasitas 
    { {     301}, { 13} }, // ertekadas
    { {     302}, { 14} }, // be       
    { {     303}, { 15} }, // ki       
    { {     304}, { 16} }, // elagazas 
    { {     305}, { 17} }, // ciklus   
    { {     277}, { 18} }, // ID       
    { {     269}, { 19} }, // STR_IN   
    { {     268}, { 20} }, // STR_OUT  
    { {     263}, { 21} }, // IF       
    { {     265}, { 22} }, // WHILE    
    { {       0}, { -7} },             
};

SR__ s_13[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       271}, { 29} }, // EQV
    { {         0}, {  0} },       
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       266}, { 30} }, // CIN
    { {         0}, {  0} },       
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       267}, { 31} }, // COUT
    { {         0}, {  0} },        
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },           
    { {       272}, { 32} }, // OPENPAR
    { {         0}, {  0} },           
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },           
    { {       272}, { 33} }, // OPENPAR
    { {         0}, {  0} },           
};

SR__ s_23[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       270}, { 34} }, // ENDL
    { {         0}, {  0} },        
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       270}, { 35} }, // ENDL
    { {         0}, {  0} },        
};

SR__ s_26[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 36} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       277}, { 43} }, // ID
    { {         0}, {  0} },      
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 44} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 45} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 46} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_34[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_35[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, { 12} },         
    { {       270}, { 47} }, // ENDL 
    { {       290}, { 48} }, // PLS  
    { {       291}, { 49} }, // MIN  
    { {       292}, { 50} }, // MUL  
    { {       293}, { 51} }, // DIV  
    { {       294}, { 52} }, // MOD  
    { {       288}, { 53} }, // LESS 
    { {       289}, { 54} }, // GRT  
    { {       287}, { 55} }, // EQUAL
    { {       285}, { 56} }, // AND  
    { {       284}, { 57} }, // OR   
    { {         0}, {  0} },         
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 58} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 59} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       270}, { 60} }, // ENDL
    { {         0}, {  0} },        
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 12} },         
    { {       270}, { 61} }, // ENDL 
    { {       290}, { 48} }, // PLS  
    { {       291}, { 49} }, // MIN  
    { {       292}, { 50} }, // MUL  
    { {       293}, { 51} }, // DIV  
    { {       294}, { 52} }, // MOD  
    { {       288}, { 53} }, // LESS 
    { {       289}, { 54} }, // GRT  
    { {       287}, { 55} }, // EQUAL
    { {       285}, { 56} }, // AND  
    { {       284}, { 57} }, // OR   
    { {         0}, {  0} },         
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 12} },            
    { {       273}, { 62} }, // CLOSEPAR
    { {       290}, { 48} }, // PLS     
    { {       291}, { 49} }, // MIN     
    { {       292}, { 50} }, // MUL     
    { {       293}, { 51} }, // DIV     
    { {       294}, { 52} }, // MOD     
    { {       288}, { 53} }, // LESS    
    { {       289}, { 54} }, // GRT     
    { {       287}, { 55} }, // EQUAL   
    { {       285}, { 56} }, // AND     
    { {       284}, { 57} }, // OR      
    { {         0}, {  0} },            
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 12} },            
    { {       273}, { 63} }, // CLOSEPAR
    { {       290}, { 48} }, // PLS     
    { {       291}, { 49} }, // MIN     
    { {       292}, { 50} }, // MUL     
    { {       293}, { 51} }, // DIV     
    { {       294}, { 52} }, // MOD     
    { {       288}, { 53} }, // LESS    
    { {       289}, { 54} }, // GRT     
    { {       287}, { 55} }, // EQUAL   
    { {       285}, { 56} }, // AND     
    { {       284}, { 57} }, // OR      
    { {         0}, {  0} },            
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 64} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 65} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 66} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 67} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 68} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 69} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 70} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 71} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 72} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       306}, { 73} }, // kifejezes
    { {       274}, { 37} }, // NUM      
    { {       275}, { 38} }, // TRUE     
    { {       276}, { 39} }, // FALSE    
    { {       277}, { 40} }, // ID       
    { {       286}, { 41} }, // NEG      
    { {       272}, { 42} }, // OPENPAR  
    { {         0}, {  0} },             
};

SR__ s_58[] =
{
    { { REQ_DEF}, {   9} },         
    { {     290}, {  48} }, // PLS  
    { {     291}, {  49} }, // MIN  
    { {     292}, {  50} }, // MUL  
    { {     293}, {  51} }, // DIV  
    { {     294}, {  52} }, // MOD  
    { {     288}, {  53} }, // LESS 
    { {     289}, {  54} }, // GRT  
    { {     287}, {  55} }, // EQUAL
    { {       0}, { -34} },         
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, { 12} },            
    { {       273}, { 74} }, // CLOSEPAR
    { {       290}, { 48} }, // PLS     
    { {       291}, { 49} }, // MIN     
    { {       292}, { 50} }, // MUL     
    { {       293}, { 51} }, // DIV     
    { {       294}, { 52} }, // MOD     
    { {       288}, { 53} }, // LESS    
    { {       289}, { 54} }, // GRT     
    { {       287}, { 55} }, // EQUAL   
    { {       285}, { 56} }, // AND     
    { {       284}, { 57} }, // OR      
    { {         0}, {  0} },            
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       259}, { 75} }, // OPENBRAC
    { {         0}, {  0} },            
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       259}, { 76} }, // OPENBRAC
    { {         0}, {  0} },            
};

SR__ s_64[] =
{
    { { REQ_DEF}, {   4} },       
    { {     292}, {  50} }, // MUL
    { {     293}, {  51} }, // DIV
    { {     294}, {  52} }, // MOD
    { {       0}, { -24} },       
};

SR__ s_65[] =
{
    { { REQ_DEF}, {   4} },       
    { {     292}, {  50} }, // MUL
    { {     293}, {  51} }, // DIV
    { {     294}, {  52} }, // MOD
    { {       0}, { -25} },       
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_67[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_69[] =
{
    { { REQ_DEF}, {   6} },       
    { {     290}, {  48} }, // PLS
    { {     291}, {  49} }, // MIN
    { {     292}, {  50} }, // MUL
    { {     293}, {  51} }, // DIV
    { {     294}, {  52} }, // MOD
    { {       0}, { -29} },       
};

SR__ s_70[] =
{
    { { REQ_DEF}, {   6} },       
    { {     290}, {  48} }, // PLS
    { {     291}, {  49} }, // MIN
    { {     292}, {  50} }, // MUL
    { {     293}, {  51} }, // DIV
    { {     294}, {  52} }, // MOD
    { {       0}, { -30} },       
};

SR__ s_71[] =
{
    { { REQ_DEF}, {   8} },        
    { {     290}, {  48} }, // PLS 
    { {     291}, {  49} }, // MIN 
    { {     292}, {  50} }, // MUL 
    { {     293}, {  51} }, // DIV 
    { {     294}, {  52} }, // MOD 
    { {     288}, {  53} }, // LESS
    { {     289}, {  54} }, // GRT 
    { {       0}, { -31} },        
};

SR__ s_72[] =
{
    { { REQ_DEF}, {   9} },         
    { {     290}, {  48} }, // PLS  
    { {     291}, {  49} }, // MIN  
    { {     292}, {  50} }, // MUL  
    { {     293}, {  51} }, // DIV  
    { {     294}, {  52} }, // MOD  
    { {     288}, {  53} }, // LESS 
    { {     289}, {  54} }, // GRT  
    { {     287}, {  55} }, // EQUAL
    { {       0}, { -32} },         
};

SR__ s_73[] =
{
    { { REQ_DEF}, {  10} },         
    { {     290}, {  48} }, // PLS  
    { {     291}, {  49} }, // MIN  
    { {     292}, {  50} }, // MUL  
    { {     293}, {  51} }, // DIV  
    { {     294}, {  52} }, // MOD  
    { {     288}, {  53} }, // LESS 
    { {     289}, {  54} }, // GRT  
    { {     287}, {  55} }, // EQUAL
    { {     285}, {  56} }, // AND  
    { {       0}, { -33} },         
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, { 13} },             
    { {       298}, { 77} }, // torzs    
    { {       300}, { 12} }, // utasitas 
    { {       301}, { 13} }, // ertekadas
    { {       302}, { 14} }, // be       
    { {       303}, { 15} }, // ki       
    { {       304}, { 16} }, // elagazas 
    { {       305}, { 17} }, // ciklus   
    { {       277}, { 18} }, // ID       
    { {       269}, { 19} }, // STR_IN   
    { {       268}, { 20} }, // STR_OUT  
    { {       263}, { 21} }, // IF       
    { {       265}, { 22} }, // WHILE    
    { {         0}, {  0} },             
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, { 13} },             
    { {       298}, { 78} }, // torzs    
    { {       300}, { 12} }, // utasitas 
    { {       301}, { 13} }, // ertekadas
    { {       302}, { 14} }, // be       
    { {       303}, { 15} }, // ki       
    { {       304}, { 16} }, // elagazas 
    { {       305}, { 17} }, // ciklus   
    { {       277}, { 18} }, // ID       
    { {       269}, { 19} }, // STR_IN   
    { {       268}, { 20} }, // STR_OUT  
    { {       263}, { 21} }, // IF       
    { {       265}, { 22} }, // WHILE    
    { {         0}, {  0} },             
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       260}, { 79} }, // CLOSEBRAC
    { {         0}, {  0} },             
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       260}, { 80} }, // CLOSEBRAC
    { {         0}, {  0} },             
};

SR__ s_79[] =
{
    { { REQ_DEF}, {   2} },        
    { {     264}, {  81} }, // ELSE
    { {       0}, { -17} },        
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       259}, { 82} }, // OPENBRAC
    { {         0}, {  0} },            
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, { 13} },             
    { {       298}, { 83} }, // torzs    
    { {       300}, { 12} }, // utasitas 
    { {       301}, { 13} }, // ertekadas
    { {       302}, { 14} }, // be       
    { {       303}, { 15} }, // ki       
    { {       304}, { 16} }, // elagazas 
    { {       305}, { 17} }, // ciklus   
    { {       277}, { 18} }, // ID       
    { {       269}, { 19} }, // STR_IN   
    { {       268}, { 20} }, // STR_OUT  
    { {       263}, { 21} }, // IF       
    { {       265}, { 22} }, // WHILE    
    { {         0}, {  0} },             
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       260}, { 84} }, // CLOSEBRAC
    { {         0}, {  0} },             
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 52 "cflex.y"
        {
         
         }
        break;

        case 2:
#line 59 "cflex.y"
        {
         
         }
        break;

        case 3:
#line 66 "cflex.y"
        {
         
         }
        break;

        case 4:
#line 71 "cflex.y"
        {
         
         }
        break;

        case 5:
#line 78 "cflex.y"
        {
         
         if( szimbolumtabla.count(*d_vsp__[-1].szoveg) > 0 )
         {
         std::stringstream ss;
         ss << "Ujradeklaralt valtozo: " << *d_vsp__[-1].szoveg << ".\n"
         << "Korabbi deklaracio sora: " << szimbolumtabla[*d_vsp__[-1].szoveg].def_sora << std::endl;
         error( ss.str().c_str() );
         }
         szimbolumtabla[*d_vsp__[-1].szoveg] = var_data(d_loc__.first_line,Egesz);
         delete d_vsp__[-1].szoveg;
         }
        break;

        case 6:
#line 92 "cflex.y"
        {
         
         if( szimbolumtabla.count(*d_vsp__[-1].szoveg) > 0 )
         {
         std::stringstream ss;
         ss << "Ujradeklaralt valtozo: " << *d_vsp__[-1].szoveg << ".\n"
         << "Korabbi deklaracio sora: " << szimbolumtabla[*d_vsp__[-1].szoveg].def_sora << std::endl;
         error( ss.str().c_str() );
         }
         szimbolumtabla[*d_vsp__[-1].szoveg] = var_data(d_loc__.first_line,Logikai);
         delete d_vsp__[-1].szoveg;
         }
        break;

        case 7:
#line 108 "cflex.y"
        {
         
         }
        break;

        case 8:
#line 113 "cflex.y"
        {
         
         }
        break;

        case 9:
#line 120 "cflex.y"
        {
         
         }
        break;

        case 10:
#line 125 "cflex.y"
        {
         
         }
        break;

        case 11:
#line 130 "cflex.y"
        {
         
         }
        break;

        case 12:
#line 135 "cflex.y"
        {
         
         }
        break;

        case 13:
#line 140 "cflex.y"
        {
         
         }
        break;

        case 14:
#line 147 "cflex.y"
        {
         
         if( szimbolumtabla.count( *d_vsp__[-3].szoveg ) == 0 )
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": A(z) '" << *d_vsp__[-3].szoveg << "' valtozo nincs deklaralva." << std::endl;
         error( ss.str().c_str() );
         }
         if( szimbolumtabla[*d_vsp__[-3].szoveg].tipus != d_vsp__[-1].kif->ktip)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Az ertekadas jobb- es baloldalan kulonbozo tipusu kifejezesek allnak." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line );
         delete d_vsp__[-3].szoveg;
         delete d_vsp__[-1].kif;
         }
        break;

        case 15:
#line 169 "cflex.y"
        {
         
         if( szimbolumtabla.count( *d_vsp__[-1].szoveg ) == 0 )
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": A(z) '" << *d_vsp__[-1].szoveg << "' valtozo nincs deklaralva." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line );
         delete d_vsp__[-1].szoveg;
         }
        break;

        case 16:
#line 184 "cflex.y"
        {
         
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line );
         delete d_vsp__[-1].kif;
         }
        break;

        case 17:
#line 193 "cflex.y"
        {
         
         if( d_vsp__[-4].kif->ktip != Logikai )
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Nem logikai tipusu az elagazas feltetele." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.utasitas = new utasitas_leiro( d_vsp__[-4].kif->sor );
         delete d_vsp__[-4].kif;
         }
        break;

        case 18:
#line 206 "cflex.y"
        {
         
         if( d_vsp__[-8].kif->ktip != Logikai )
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Nem logikai tipusu az elagazas feltetele." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.utasitas = new utasitas_leiro( d_vsp__[-8].kif->sor );
         delete d_vsp__[-8].kif;
         }
        break;

        case 19:
#line 221 "cflex.y"
        {
         
         if( d_vsp__[-4].kif->ktip != Logikai )
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Nem logikai tipusu a ciklus feltetele." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.utasitas = new utasitas_leiro( d_vsp__[-4].kif->sor );
         delete d_vsp__[-4].kif;
         }
        break;

        case 20:
#line 236 "cflex.y"
        {
         
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz );
         }
        break;

        case 21:
#line 242 "cflex.y"
        {
         
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         }
        break;

        case 22:
#line 248 "cflex.y"
        {
         
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         }
        break;

        case 23:
#line 254 "cflex.y"
        {
         
         if( szimbolumtabla.count( *d_vsp__[0].szoveg ) == 0 )
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": A(z) '" << *d_vsp__[0].szoveg << "' valtozo nincs deklaralva." << std::endl;
         error( ss.str().c_str() );
         }
         var_data vl = szimbolumtabla[*d_vsp__[0].szoveg];
         d_val__.kif = new kifejezes_leiro( vl.def_sora, vl.tipus );
         }
        break;

        case 24:
#line 267 "cflex.y"
        {
         
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[-2].kif->sor << ": A '+' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[0].kif->sor << ": A '+' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 25:
#line 287 "cflex.y"
        {
         
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[-2].kif->sor << ": A '-' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[0].kif->sor << ": A '-' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 26:
#line 307 "cflex.y"
        {
         
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[-2].kif->sor << ": A '*' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[0].kif->sor << ": A '*' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 27:
#line 327 "cflex.y"
        {
         
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[-2].kif->sor << ": A 'div' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[0].kif->sor << ": A 'div' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 28:
#line 347 "cflex.y"
        {
         
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[-2].kif->sor << ": A 'mod' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[0].kif->sor << ": A 'mod' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 29:
#line 367 "cflex.y"
        {
         
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[-2].kif->sor << ": A '<' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[0].kif->sor << ": A '<' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 30:
#line 387 "cflex.y"
        {
         
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[-2].kif->sor << ": A '>' operator baloldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::stringstream ss;
         ss << d_vsp__[0].kif->sor << ": A '>' operator jobboldalan nem egesz tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 31:
#line 407 "cflex.y"
        {
         
         if( d_vsp__[-2].kif->ktip != d_vsp__[0].kif->ktip )
         {
         std::stringstream ss;
         ss << d_vsp__[-2].kif->sor << ": Az '=' operator jobb- es baloldalan kulonbozo tipusu kifejezesek allnak." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 32:
#line 421 "cflex.y"
        {
         
         if( d_vsp__[-2].kif->ktip != Logikai )
         {
         std::stringstream ss;
         ss << d_vsp__[-2].kif->sor << ": Az 'and' operator baloldalan nem logikai tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         if( d_vsp__[0].kif->ktip != Logikai )
         {
         std::stringstream ss;
         ss << d_vsp__[0].kif->sor << ": Az 'and' operator jobboldalan nem logikai tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 33:
#line 441 "cflex.y"
        {
         
         if( d_vsp__[-2].kif->ktip != Logikai )
         {
         std::stringstream ss;
         ss << d_vsp__[-2].kif->sor << ": Az 'and' operator baloldalan nem logikai tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         if( d_vsp__[0].kif->ktip != Logikai )
         {
         std::stringstream ss;
         ss << d_vsp__[0].kif->sor << ": Az 'and' operator jobboldalan nem logikai tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 34:
#line 461 "cflex.y"
        {
         
         if( d_vsp__[0].kif->ktip != Logikai )
         {
         std::stringstream ss;
         ss << d_vsp__[0].kif->sor << ": A 'NEM' operator utan nem logikai tipusu kifejezes all." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         delete d_vsp__[0].kif;
         }
        break;

        case 35:
#line 474 "cflex.y"
        {
         
         d_val__.kif = d_vsp__[-1].kif;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



